######脚本相关路径和分类
#completed：硬链接目录，category：分类目录
####/最顶层目录/分类/completed(参数填充处可改）：你硬链接所在地方  分类在前，硬链接目录在后
####your_Way根据你的媒体库目录类型来改变
your_path=downloads
completed=completed
your_Way=$category/$completed

###下面几个参数都是根据docker内媒体保存路径来填充的
###your_category这个参数是，只要保存路径有里面的几个内容都会匹配到该脚本，运行该脚本
your_category=日剧|动漫|电影ISO|音乐视频|华语剧|music|音乐视频|音乐视频ISO|剧集ISO|高清韩剧|电影|电影2|欧美剧|小黄片
###your_category_tv，只要保存路径包含里面的内容就会把它当成剧集来硬链接和整理
your_category_tv=日剧|动漫|高清韩剧|华语剧|剧集ISO|欧美剧
###your_category_movies，只要保存路径包含里面的内容就会把它当成电影来硬链接和整理
your_category_movies=电影|电影ISO|电影2
###your_category_direct，只要保存路径包含里面的内容就会把它直接硬链接，不进行额外操作
your_category_direct=music|音乐视频|音乐视频ISO
###your_category_emby，只要保存路径包含里面的内容只会启动刮削，不会进行额外操作
your_category_emby=小黄片

###以下这三个参数可以不改动，只是为了刮削更精准
###your_category_KR以下这三个，只要保存路径包含里面的内容就会把它当成对应的内容来刮削。如your_category_zhcn，就只会将它当成华语剧来刮削，降低误判率
your_category_KR=高清韩剧
your_category_JP=日语剧
your_category_zhcn=华语剧


####下面这个是读取qb的分类来进行操作
your_Category=Vertex
####Emby参数填充##
Emby=192.168.1.196:8096
Emby_Apikey=11
###tmdb参数填充
api_key=111

##进阶功能

###qbittorrent_delete.sh脚本参数
qbittorrent_url=192.168.1.196:9090
##main脚本运行历史，填的地址都是运行脚本后能访问到的地址
qbittorrent_main_history=/data/diy/main_history.log

###transmission_add.sh和transmission_delete.sh脚本参数
transmission_url=localhost:9090
##main脚本运行历史，填的地址都是运行脚本后能访问到的地址
transmission_main_history=/mnt/脚本/main_history.log

##相关tg通知参数
#用户ID或频道、群ID
chat_ID=111
#TG机器人token
TOKEN=1111

##emby.delete.sh脚本参数
##emby.delete.sh脚本要删除的顶层目录
emby_delete_volume=volume1|volume2|volume3
##container_name填入你做种的下载器,容器名
container_name=transmission
###delete_script填入你的对应下载器的删除脚本在对应下载器容器里的路径
delete_scripts=/config/transmission_delete.sh
